services:
  ctfd:
    image: ctfd/ctfd:3.8.6
    user: root
    restart: always
    expose:
        - "8000"
    environment:
        - UPLOAD_FOLDER=/var/uploads
        - LOG_FOLDER=/var/log/CTFd
        - DATABASE_URL=mysql+pymysql://ctfd:ctfd@db/ctfd
        - REDIS_URL=redis://cache:6379
        - REVERSE_PROXY=true
    volumes:
        - .data/CTFd/logs:/var/log/CTFd
        - .data/CTFd/uploads:/var/uploads
    depends_on:
        - db
        - cache
    networks:
        - default
        - internal

  db:
    image: mariadb:10.11.8
    restart: always
    environment:
        - MARIADB_ROOT_PASSWORD=ctfd
        - MARIADB_USER=ctfd
        - MARIADB_PASSWORD=ctfd
        - MARIADB_DATABASE=ctfd
        - MARIADB_AUTO_UPGRADE=1
    volumes:
        - .data/mysql:/var/lib/mysql
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]
    networks:
        - internal

  cache:
    image: redis:7.4.2-alpine3.21
    restart: always
    volumes:
        - .data/redis:/data
    networks:
        - internal

  nginx:
    restart: always
    image: nginx:1.28.2-alpine3.23
    ports:
        - 80:80
        - 443:443
    volumes:
        - ./data/nginx:/etc/nginx/conf.d
        - ./data/certbot/conf:/etc/letsencrypt
        - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    networks:
        - default
        - internal

  certbot:
    restart: always
    image: certbot/certbot:v5.2.2
    volumes:
        - ./data/certbot/conf:/etc/letsencrypt
        - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  default:
  internal:
    internal: true
